
---
- hosts: localhost
  become: true
  tasks:
   - name: install Docker
     apt:
       name: docker
       state: present
       update_cache: true
   - name: start Docker
     service:
       name: docker
       state: started
   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present
   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present
   - name: add Kubernetes apt_repository
     get_url:
      url: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      dest: ./
   - name: install kubelet
     apt:
        name: kubelet
        state: present
        update_cache: true
   - name: install kubeadm
     apt:
        name: kubeadm
        state: present
   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started
- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
        name: kubectl
        state: present
        allow_downgrade: yes
